### ISSUE TITLE
with actualDuration being private import fails - "latest working commit updated TODOs"

### ISSUE THREAD

**Issue by lpetflo** [inf18229/SWEII_CASE_TOOL#2]
/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=53672:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/target/classes:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.transaction.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.annotation.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.jms.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.resource.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.servlet.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.ejb.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.persistence.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.servlet.jsp.jar:/Users/florianschiffel/Duale Hochschule Baden-Württemberg Stuttgart/Maier Stefan (inf18229) - TEAMORDNER_DHBW/SWE/Software-Projekt/SWEII_CASE_TOOL/lib/javax.servlet.jsp.jstl.jar:/Users/florianschiffel/.m2/repository/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar:/Users/florianschiffel/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar:/Users/florianschiffel/.m2/repository/com/sun/xml/bind/jaxb-core/2.3.0/jaxb-core-2.3.0.jar:/Users/florianschiffel/.m2/repository/com/sun/xml/bind/jaxb-impl/2.3.0/jaxb-impl-2.3.0.jar" main
View erstellt
Öffne Projekt wurde gedrückt.
com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
Klasse enthält zwei Eigenschaften mit demselben Namen "actualDuration"
	this problem is related to the following location:
		at public double MODEL.PROJECTDATA.M_PROJECTDATA_FUNCTIONPOINTESTIMATION.getActualDuration()
		at MODEL.PROJECTDATA.M_PROJECTDATA_FUNCTIONPOINTESTIMATION
		at MODEL.PROJECTDATA.M_PROJECTDATA_FUNCTIONPOINTESTIMATION MODEL.PROJECTDATA.M_PROJECTDATA.m_projectData_functionPointEstimation
		at MODEL.PROJECTDATA.M_PROJECTDATA
	this problem is related to the following location:
		at public double MODEL.PROJECTDATA.M_PROJECTDATA_FUNCTIONPOINTESTIMATION.actualDuration
		at MODEL.PROJECTDATA.M_PROJECTDATA_FUNCTIONPOINTESTIMATION
		at MODEL.PROJECTDATA.M_PROJECTDATA_FUNCTIONPOINTESTIMATION MODEL.PROJECTDATA.M_PROJECTDATA.m_projectData_functionPointEstimation
		at MODEL.PROJECTDATA.M_PROJECTDATA

	at com.sun.xml.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:106)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:471)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:303)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:297)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:286)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:409)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at MODEL.M_IMPORT.importProject(M_IMPORT.java:48)
	at CONTROLLER.C_START.notifyOpen(C_START.java:89)
	at VIEW.V_START$2.actionPerformed(V_START.java:49)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
General Controller created

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

**Comment by lpetflo** [comment]
Not occurring anymore since "made count private, fixed actual Duration problem?" commit

**Comment by maier-s** [comment]
close issue?

**Comment by lpetflo** [comment]
David soll mal noch kurz drüberschauen, dann ja.
Wir sollten es nur im Hinterkopf haben, falls es nochmal kommt.

**Comment by lpetflo** [comment]
Did not happen again, therefore closed, but keep it in mind if something similar should happen.
